services:
  imapsync-manager:
    build: https://github.com/dragonal42/imapsync-manager.git#main
    container_name: imapsync-manager
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Paris
      - SMTP_HOST=mail.billiar.info
      - SMTP_PORT=587
      - SMTP_FROM=alain@billiar.info
      - SMTP_USER=alain@billiar.info
      - SMTP_PASS=Chavaler&43
    volumes:
      - ./data:/app/data
    restart: unless-stopped
